# Generated by Django 4.2.2 on 2023-06-13 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('col_offset', models.IntegerField()),
                ('end_col_offset', models.IntegerField()),
                ('filename', models.CharField(max_length=255)),
                ('issue_confidence', models.CharField(max_length=255)),
                ('issue_cwe_id', models.IntegerField()),
                ('issue_cwe_link', models.URLField()),
                ('issue_severity', models.CharField(max_length=255)),
                ('issue_text', models.TextField()),
                ('line_number', models.IntegerField()),
                ('line_range', models.JSONField()),
                ('more_info', models.URLField()),
                ('test_id', models.CharField(max_length=255)),
                ('test_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issues', models.ManyToManyField(to='core.issue')),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, unique=True)),
                ('results', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.result')),
            ],
        ),
    ]
